#!/usr/bin/env python
import os, glob

tests  = ['icestick', 'goboard', 'hx8kboard']
tests += ['tinyfpga/B2', 'tinyfpga/BX']
tests += ['upduino']
tests += ['gp4devboard']
tests += ['megawing/papiloone', 'megawing/papiliopro']

def build():
    for test in tests:
        if os.path.isdir(test):
            if not test[0] == '_' and not test.startswith('test_'):
                os.system('cd %s; ./bake; cd ..' % test)

build()
