#!/usr/bin/env python3
import sys
from mako.template import Template

import os
import csv

class Pin:
    def __init__(self,name):
        self.name = name
        self.gpio = False
        self.clock = False

def readpins(part, package):
    name = part + package + '.csv'
    dir = os.path.join(os.path.dirname(__file__), 'pins')
    filename = os.path.join(dir,name)

    f = open(filename)
    row = csv.reader(f)

    header = row.__next__()
    #print(header)

    pins = []
    for data in row:
        name = data[0]
        pin = Pin(name)
        if data[3].startswith('IO'):
            pin.gpio = True
            if data[3].find('GCLK') != -1:
                pin.clock = True
        pins.append(pin)

    return pins


def main():
    argc = len(sys.argv)
    if argc < 3:
        print( "usage: prep6 file.t file.py" )
        sys.exit(0)

    temp = sys.argv[1]
    file = sys.argv[2]

    tqg144 = readpins('6slx9','tqg144')
    ftg256 = readpins('6slx9','ftg256')

    temp = Template(open(temp).read())
    temp = temp.render(ftg256=ftg256, tqg144=tqg144)

    file = open(file, 'w')
    file.write(temp)

if __name__ == "__main__":
    main()
