#!/usr/bin/env python
import os, glob
from os.path import join, exists
from fabricate import main, autoclean, outofdate, run

BUILD = 'build'
GOLD = 'gold'

BOARD = 'icestick'

tests = glob.glob('*.py')

def build():
    for test in tests:
        if test[0] != '_' and not test.startswith('test_'):
            base, suffix = test.split('.')
            compile(base)

def compile(base):
    magma(base)
    regress(base)

def magma(base):
    run('magma','-b',BOARD,base)

def regress(base):
    u = base+'.pcf'
    v = base+'.v'
    buildu, goldu = join(BUILD,u), join(GOLD,u)
    buildv, goldv = join(BUILD,v), join(GOLD,v)
    if exists(goldv):
        run('cmp',buildv,goldv)
    if exists(goldu):
        run('cmp',buildu,goldu)

def gold():
    os.system('cp %s/*.v %s' % (BUILD, GOLD))
    os.system('cp %s/*.pcf %s' % (BUILD, GOLD))

def check():
    return int(outofdate(build))

def clean():
    autoclean()

def rebuild():
    clean()
    build()

main()
