#!/usr/bin/env python
import os

tests = ['ice40']

def build():
    for test in tests:
        if os.path.isdir(test):
            if not test[0] == '_' and not test.startswith('test_'):
                os.system('cd %s; ./bake; cd ..' % test)

build()
#gold()
