#!/usr/bin/env python3
from magma import compile
from magma.circuit import __magma_clear_circuit_cache as clear_circuit_cache
from testharness import test
from mantle import And, Or

tests = [
   ('and2', lambda n: And(n), lambda x0, x1: x0&x1),
   ('or2',  lambda n: Or(n),  lambda x0, x1: x0|x1)
]

for t in tests:
    name = t[0]
    print(name)
    clear_circuit_cache()
    main = test(t[1], t[2])
    compile(name, main)


