#!/usr/bin/env python3
import os, glob
import time

for test in glob.glob('build/*.v'):
    name = os.path.split(test)[1]
    name = os.path.splitext(name)[0]
    os.system('./run {}'.format(name))
    time.sleep(2)

