#!/usr/bin/env python2
import os, glob
from os.path import join, exists
from fabricate import main, autoclean, run

BOARD = 'icestick'

tests = glob.glob('*.py')

def build():
    for test in tests:
        if not test.startswith('_'):
            base, suffix = test.split('.')
            compile(base)

def compile(base):
    run('magma','-b',BOARD,base)

def clean():
    autoclean()

def gold():
    os.system('cp %s/*{.v,.ucf} %s' % (BUILD, GOLD))

main()
